fix formater to allow bytes output from serializer
b2wdigital/aiologger pull request #116
Opened 2020-10-06 17:34 UTC by t1m0t

Fixes #115

2020-10-06 20:00 UTC, t1m0t commented
The deployment fails to install a dependency (orjson) required for testing purpose. Would need help for this to work in travis ci..

2020-10-09 23:26 UTC, daltonmatos requested changes
Just change one of the `format()` str/byte detection code and add a new testcase that checks the actual content of the result returned by `format()`.

Thanks for the PR.

2020-10-09 23:26 UTC, daltonmatos commented on aiologger/formatters/json.py
> +            return result.decode('utf-8')
Hello @t1m0t,

could you please change this implementation to use the same login used in https://github.com/b2wdigital/aiologger/blob/7a33d2f94ecdde60b906039d0abda8002869eee2/aiologger/formatters/json.py#L164-L167?

Thanks.

2020-10-09 23:26 UTC, daltonmatos commented on tests/formatters/json/test_extended_json_formatter.py
> +    def test_json_properly_serialized_when_bytes_object(self):
Maybe a better test check would be to effectively decode the original bytes and then compare to the result returned by the formatter.

Here we are checking only the type of the return, but not the real value.

Thanks.

2020-10-09 23:32 UTC, daltonmatos commented on tests/formatters/json/test_extended_json_formatter.py
> +    def test_json_properly_serialized_when_bytes_object(self):
Would you also mind adding this same test (checking the type) but when using `json` module, please? :smile:

2020-10-10 11:16 UTC, t1m0t commented on aiologger/formatters/json.py
> +            return result.decode('utf-8')
corrected
thanks

2020-10-10 20:55 UTC, t1m0t commented on aiologger/formatters/json.py
> +            return result.decode('utf-8')
I just pushed an update for this PR. But I have an issue which concerns unittest. He it is:
```
ERROR: test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function (tests.formatters.json.test_extended_json_formatter.ExtendedJsonFormatterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fff/aiologger/tests/formatters/json/test_extended_json_formatter.py", line 190, in test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function
    self.formatter.format(self.record)
  File "/home/fff/aiologger/formatters/json.py", line 154, in format
    return self._serializer_ensure_str(msg=msg)
  File "/home/fff/aiologger/formatters/base.py", line 260, in _serializer_ensure_str
    raise Exception(f'ERROR: serialized object must be of str or bytes type, given {result} with type {resType}')
Exception: ERROR: serialized object must be of str or bytes type, given <MagicMock name='serializer()' id='140625811159024'> with type <class 'unittest.mock.MagicMock'>

----------------------------------------------------------------------
Ran 13 tests in 0.130s

FAILED (errors=1)
```
Does someone has a clue to fix this?
Thanks

2020-10-10 20:56 UTC, t1m0t commented
I just pushed an update for this PR. But I have an issue which concerns unittest. He it is:
```
ERROR: test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function (tests.formatters.json.test_extended_json_formatter.ExtendedJsonFormatterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fff/aiologger/tests/formatters/json/test_extended_json_formatter.py", line 190, in test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function
    self.formatter.format(self.record)
  File "/home/fff/aiologger/formatters/json.py", line 154, in format
    return self._serializer_ensure_str(msg=msg)
  File "/home/fff/aiologger/formatters/base.py", line 260, in _serializer_ensure_str
    raise Exception(f'ERROR: serialized object must be of str or bytes type, given {result} with type {resType}')
Exception: ERROR: serialized object must be of str or bytes type, given <MagicMock name='serializer()' id='140625811159024'> with type <class 'unittest.mock.MagicMock'>

----------------------------------------------------------------------
Ran 13 tests in 0.130s

FAILED (errors=1)
```
Does someone has a clue to fix this?
Thanks

2020-10-10 20:57 UTC, t1m0t commented on tests/formatters/json/test_extended_json_formatter.py
> +    def test_json_properly_serialized_when_bytes_object(self):
Just pushed an update. Please let me know if it is fine.
Thanks.

2020-10-11 19:20 UTC, daltonmatos commented
Hello @t1m0t,

I just merged #117 that upates pip and pipenv. This should make it possible do install `orjson` when running on CircleCI. Could you please update your branch and check if `orjson` will be conrrectly installed when running the build for your PR?

Thanks,

2020-10-11 20:15 UTC, daltonmatos requested changes
`serializer_kwargs` comes from `ExtendedLogRecord` and it should be passed along until `self.serializer(...)` is called.

2020-10-11 20:15 UTC, daltonmatos commented on aiologger/formatters/json.py
> +
Before this modification, the call to `self.serializer()` received `**record.serializer_kwargs`, but now that this call is inside the newly created `self._serializer_ensure_str()`, it does not receive `record` so all the logic that ensures that the custom serializer receives these extra kwargs cannot be tested.

I think we should pass along `record` so we can check this behavior.

2020-10-11 20:15 UTC, daltonmatos commented on aiologger/formatters/base.py
> +                msg, default=self._default_handler, **msg.serializer_kwargs
`**serializer_kwargs` comes from the original `ExtendedLogRecord` object.

Also I think we could always pass `**serializer_kwargs` and to do so ensure that its default value is `{}` (which I thinks it already is.

Actually this field is alreay required for `ExtendedLogRecord`:
https://github.com/b2wdigital/aiologger/blob/b41004cf53267fc0999fa9f1f83244c226562fa4/aiologger/records.py#L136

I think we can just pass `**serializer_kwargs` every time (and not have the `if hasattr(...)`).

2020-10-11 20:21 UTC, daltonmatos commented
> Does someone have a clue to fix this?

In this case we should remove the mock from this test. The easiest way to do this is to implement a simple "stub" serializer to the formatter used in this test. This serializer could just produce the final msg and add all received `serialzed_krwags`. This way we would be able do check that the returned msg has all original fields (from `self.record`) + all `serializer_kwargs` (from `self.record.serializer_kwargs`).

I tried to draft this code and discovered a bug on the newly created `self._ensure_serializer_str()` method. The details are on the new review I made.

2020-10-12 12:47 UTC, t1m0t commented on aiologger/formatters/json.py
> +
It has been fixed in this last [commit](https://github.com/b2wdigital/aiologger/pull/116/commits/e8a7b089b86db63410f16b7840c67539f7e32b7f).
I've added `record` in the parameter of `_serializer_ensure_str` and changed the call of `serializer(...)` with `record` instead of `msg` when the attribute `serializer_kwargs` of record exists (in case of `ExtendedLogRecord`).

2020-10-12 12:52 UTC, t1m0t commented on aiologger/formatters/base.py
> +                msg, default=self._default_handler, **msg.serializer_kwargs
Please see the above [comment](https://github.com/b2wdigital/aiologger/pull/116#discussion_r503272083)  regarding this.

2020-10-12 13:01 UTC, t1m0t commented
> > Does someone have a clue to fix this?
> 
> In this case we should remove the mock from this test. The easiest way to do this is to implement a simple "stub" serializer to the formatter used in this test. This serializer could just produce the final msg and add all received `serialzed_krwags`. This way we would be able do check that the returned msg has all original fields (from `self.record`) + all `serializer_kwargs` (from `self.record.serializer_kwargs`).
> 
> I tried to draft this code and discovered a bug on the newly created `self._ensure_serializer_str()` method. The details are on the new review I made.

Thanks. Working on the last issue regarding the test `test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function` in `tests/formatters/json/test_extended_json_formatter.py` which is failing due to the new implementation of  `format` method with `_serializer_ensure_str` and with the help of your comment @daltonmatos .

2020-10-12 13:44 UTC, t1m0t commented
> ## Todo
> 
>     * [ ]  Move `_serializer_ensure_str()` to `JsonFormatter`. It's currenlty in`Formatter`, which doesn't have a `formatter` attribute.

Done with this [commit](https://github.com/b2wdigital/aiologger/pull/116/commits/5b234085543c434d024d429693ec3fc999b22200).

2020-10-12 14:26 UTC, daltonmatos requested changes
I think we can make `self._serializer_ensure_str()` receive the `record` parameter as a required parameter.

2020-10-12 14:26 UTC, daltonmatos commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
Since this method is called from `self.formatter()` (which always has a `record` parameter) we can remove the `Optional[]` from this method.
This will probably fix the `lint` error that is now showing when running CI.

```
aiologger/formatters/json.py:94: error: Item "None" of "Optional[ExtendedLogRecord]" has no attribute "serializer_kwargs"

```

2020-10-12 14:27 UTC, daltonmatos commented
Now that we have the CI effectively running we can now see the output from the linter and formatter, I will add some more bullet points to the PR description.

2020-10-12 14:35 UTC, t1m0t commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
Thank you for this review. 
Since `JsonFormatter.format` doesn't need a `record` to get its `serializer_kwargs` whereas `ExtendedJsonFormatter.format` needs it as per the base implementation. My opinion is that it makes `JsonFormatter.format` optional.

2020-10-12 14:44 UTC, daltonmatos commented
About the test that is failing, The fix could be something along these lines:

```diff
diff --git a/tests/formatters/json/test_extended_json_formatter.py b/tests/formatters/json/test_extended_json_formatter.py
index b867149..f130d03 100644
--- a/tests/formatters/json/test_extended_json_formatter.py
+++ b/tests/formatters/json/test_extended_json_formatter.py

 class ExtendedJsonFormatterTests(unittest.TestCase):
     def setUp(self):
@@ -176,6 +176,10 @@ class ExtendedJsonFormatterTests(unittest.TestCase):
     def test_serialized_kwargs_record_attr_is_passed_to_instance_serialized_function(
         self
     ):
+        def _serializer(msg, default, **kwargs):
+            data = json.dumps({**msg, **kwargs})
+            return data
+
         self.record.serializer_kwargs = {"indent": 2, "sort_keys": True}
         expected_msg = {
             "logged_at": ANY,
@@ -186,14 +190,13 @@ class ExtendedJsonFormatterTests(unittest.TestCase):
             "msg": {"dog": "Xablau", "action": "bark"},
         }
 
-        with patch.object(self.formatter, "serializer") as serializer:
-            self.formatter.format(self.record)
-            serializer.assert_called_once_with(
-                expected_msg,
-                indent=2,
-                sort_keys=True,
-                default=self.formatter._default_handler,
-            )
+        self.formatter.serializer = _serializer
+        returned_msg = self.formatter.format(self.record)
+        self.assertEqual(
+            {**expected_msg, **self.record.serializer_kwargs},
+            json.loads(returned_msg),
+        )
 ```

And then the new `expected_msg` should be the original + all fields from `self.record.serializer_kwargs`.

Also, the `default` argument is needed because the serializer is called receiving a method on this parameter and since a method is not JSON Serializable (`default` would be incorporated into `kwargs` if not passed explicitly) we would not be able do add all `**kwargs` to the returned msg.

2020-10-12 15:11 UTC, t1m0t commented
> About the test that is failing, The fix could be something along these lines:
> ...

Thanks. I've implemented the suggested test in this new [commit](https://github.com/b2wdigital/aiologger/pull/116/commits/2507e5dde0718a465efdb84b2e2bb9f8c3a29202).

2020-10-12 15:26 UTC, daltonmatos commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
OK. So maybe to fix the linter erros we must add a `if record:` around the current code. This will garantee thta we only check for `hasattribute()` when we know `record` is not `None`.

2020-10-12 15:28 UTC, daltonmatos commented
All tests pass now. That's great! 🎉 👏🏼 

The formatting is very simple to fix. After this it will remain only the linter errors.

2020-10-12 15:45 UTC, daltonmatos commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
Hmm looking closer both `format()` methods receive a `record` parameter. I think what the linter is complaining is that the method signature is different. `Formatter` and `JsonFormatter` receives `LogRecord` and `ExtendedJsonFormatter` receives `ExtendedLogRecord`.

What we need to do is to make `mypy` accept that receiving `ExtendedLogRecord` is compatible with `LogRecord`.

2020-10-12 19:50 UTC, daltonmatos commented
Hello @t1m0t. Now the CI is green! Great!

But your pull request has lower coverage (`81.25%`) than the project (`91.43%`).

Even the coverage not being for now a required check, I think at least new code shouldn't be merged without a corresponding test case.

Specifically about this PR the `else` clause of the type check, inside `self._serializer_ensure_str()` is not being called by any tests.

I think it's important to have this logic tested. Could you add a new test case that confirms that the exception os correctly raised, please?

Thanks.

2020-10-12 19:57 UTC, t1m0t commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
Actually the linter is reading the code as it were static but it is dynamic. For instance `serializer_kwargs` can be dynamically added and is optional but linter is treating it as required.. So I added a `# type: ignore` so that the linter ignore these "errors". I think linter is not enough intelligent to understand human brain so far or maybe there is another trick to make him understand as I'm new to using this tool.

2020-10-12 20:05 UTC, t1m0t commented
@daltonmatos Thank you for the review. I will add so more tests to have a better coverage.

2020-10-12 20:06 UTC, daltonmatos commented on aiologger/formatters/json.py
> +    def _serializer_ensure_str(self, msg: dict, record: Optional[ExtendedLogRecord] = None) -> str:
Ok. Fair enough. I will try some solutions later but this shouldn't block this merge. 👍🏼👍🏼

2020-10-13 14:23 UTC, daltonmatos commented
Awesome @t1m0t !! 🎉 🎉 

One last thing. In order to keep the commit history clean could you squash all your 20 commits in one single commit? If you don't feel comfortable with swashing I can merge this PR using the Github Web UI and ask it to squash for us.

What do you prefer?

2020-10-13 14:23 UTC, daltonmatos approved these changes
Thanks for the Pull Request! 🎉

2020-10-13 17:16 UTC, t1m0t commented
@daltonmatos tried to squash but I'm not sure it is fine. Please go as you suggested. Thanks

2020-10-13 19:39 UTC, merged